version: '2'
    
services:
 
   jupyter:
     build: 
      context: .
      dockerfile: Dockerfile    
     container_name: my-jupyter     
     ports:
       - "8888:8888"     
     command: /bin/bash -c "/opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8888 --no-browser --NotebookApp.token='' --allow-root"
     volumes:
       - ./notebooks:/opt/notebooks
       - /tmp/.X11-unix:/tmp/.X11-unix
     environment: 
       - "DISPLAY=unix$DISPLAY"